[project]
name = "draw-vision"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "fidelemiakanda", email = "sefimiakanda@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "mediapipe==0.10.21",
    "numpy>=1.26,<2",
    "opencv-contrib-python>=4.11,<5",
]

[project.scripts]
draw-vision = "draw_vision:main"

[build-system]
requires = ["uv_build>=0.12.4,<0.13.0"]
build-backend = "uv_build"
